/*******************************************************************************
Copyright 2009-2012 Ellucian Company L.P. and its affiliates.
*******************************************************************************/ 
package net.hedtech.banner.query

class CriteriaOperatorFactory {

    static final operators = [equals:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.equals",
                                            operator:"=",
                                            key:"equals",
                                            dynamicQuery: {tableIdentifier, parammap-> " and $tableIdentifier.${parammap.binding} = :${parammap.key} "},
                                            formatvalue : {value -> value } ],
                                equalsignorecase:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.equals",
                                            operator:"=",
                                            key:"equalsignorecase",
                                            dynamicQuery: {tableIdentifier, parammap-> " and lower($tableIdentifier.${parammap.binding}) = lower(:${parammap.key}) "},
                                            formatvalue : {value -> value } ],
                                equalsorisnull:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.equalsorisnull",
                                            operator:"=",
                                            key:"equalsorisnull",
                                            dynamicQuery: {tableIdentifier, parammap-> " and ($tableIdentifier.${parammap.binding} = :${parammap.key} OR $tableIdentifier.${parammap.binding} IS NULL) "},
                                            formatvalue : {value -> value } ],
                                contains:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.contains",
                                            operator:"like",
                                            key:"contains",
                                            dynamicQuery: {tableIdentifier, parammap -> " and lower($tableIdentifier.${parammap.binding}) like lower(:${parammap.key}) " },
                                            formatvalue : {value -> "%${value}%" } ],
                                startswith:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.startswith",
                                            operator:"like",
                                            key:"startswith",
                                            dynamicQuery: {tableIdentifier, parammap -> " and lower($tableIdentifier.${parammap.binding}) like lower(:${parammap.key}) " },
                                            formatvalue : {value -> "${value}%" }],
                                endswith:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.endswith",
                                            operator:"like",
                                            key:"endswith",
                                            dynamicQuery: {tableIdentifier, parammap -> " and lower($tableIdentifier.${parammap.binding}) like lower(:${parammap.key}) " },
                                            formatvalue : {value -> "%${value}" }],
                                between:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.between",
                                            operator:"like",
                                            key:"between",
                                            dynamicQuery: {tableIdentifier, parammap -> " and ($tableIdentifier.${parammap.binding} between :${parammap.key} and :${parammap.key}_and) " },
                                            formatvalue : {value -> value }],
                                numericbetween:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.between",
                                            operator:"like",
                                            key:"numericbetween",
                                            dynamicQuery: {tableIdentifier, parammap -> " and ($tableIdentifier.${parammap.binding} >= :${parammap.key} and $tableIdentifier.${parammap.binding} <= :${parammap.key}_and) " },
                                            formatvalue : {value -> value }],
                                notequals:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.notequals",
                                            operator:"!=",
                                            key:"notequals",
                                            dynamicQuery: {tableIdentifier, parammap-> " and $tableIdentifier.${parammap.binding} != :${parammap.key} "},
                                            formatvalue : {value -> value }],
                                notequalsignorecase:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.notequals",
                                            operator:"!=",
                                            key:"notequalsignorecase",
                                            dynamicQuery: {tableIdentifier, parammap-> " and lower($tableIdentifier.${parammap.binding}) != lower(:${parammap.key}) "},
                                            formatvalue : {value -> value }],
                                notequalsorisnull:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.notequalsorisnull",
                                            operator:"!=",
                                            key:"notequalsorisnull",
                                            dynamicQuery: {tableIdentifier, parammap-> " and ($tableIdentifier.${parammap.binding} != :${parammap.key} OR $tableIdentifier.${parammap.binding} IS NULL) "},
                                            formatvalue : {value -> value }],
                                greaterthan:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.greaterthan",
                                            operator:">",
                                            key:"greaterthan",
                                            dynamicQuery: {tableIdentifier, parammap-> " and $tableIdentifier.${parammap.binding} > :${parammap.key}  "},
                                            formatvalue : {value -> value }],
                                greaterthanorisnull:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.greaterthanorisnull",
                                            operator:">",
                                            key:"greaterthanorisnull",
                                            dynamicQuery: {tableIdentifier, parammap-> " and ($tableIdentifier.${parammap.binding} > :${parammap.key} or $tableIdentifier.${parammap.binding} IS NULL) "},
                                            formatvalue : {value -> value }],
                                lessthan:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.lessthan",
                                            operator:"<",
                                            key:"lessthan",
                                            dynamicQuery: {tableIdentifier, parammap-> " and $tableIdentifier.${parammap.binding} < :${parammap.key} "},
                                            formatvalue : {value -> value }],
                                lessthanorisnull:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.lessthanorisnull",
                                            operator:"<",
                                            key:"lessthanorisnull",
                                            dynamicQuery: {tableIdentifier, parammap-> " and ($tableIdentifier.${parammap.binding} < :${parammap.key} or $tableIdentifier.${parammap.binding} IS NULL) "},
                                            formatvalue : {value -> value }],
                                greaterthanequals:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.greaterthanequals",
                                            operator:">=",
                                            key:"greaterthanequals",
                                            dynamicQuery: {tableIdentifier, parammap-> " and $tableIdentifier.${parammap.binding} >= :${parammap.key} "},
                                            formatvalue : {value -> value }],
                                greaterthanequalsorisnull:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.greaterthanequalsorisnull",
                                            operator:">=",
                                            key:"greaterthanequalsorisnull",
                                            dynamicQuery: {tableIdentifier, parammap-> " and ($tableIdentifier.${parammap.binding} >= :${parammap.key} or $tableIdentifier.${parammap.binding} IS NULL) "},
                                            formatvalue : {value -> value }],
                                lessthanequals:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.lessthanequals",
                                            operator:"<=",
                                            key:"lessthanequals",
                                            dynamicQuery: {tableIdentifier, parammap-> " and $tableIdentifier.${parammap.binding} <= :${parammap.key}  "},
                                            formatvalue : {value -> value }],
                                lessthanequalsorisnull:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.lessthanequalsorisnull",
                                            operator:"<=",
                                            key:"lessthanequalsorisnull",
                                            dynamicQuery: {tableIdentifier, parammap-> " and ($tableIdentifier.${parammap.binding} <= :${parammap.key} or $tableIdentifier.${parammap.binding} IS NULL) "},
                                            formatvalue : {value -> value }],
                                isnull:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.isnull",
                                            operator:"is null",
                                            key:"isnull",
                                            dynamicQuery: {tableIdentifier, parammap-> " and $tableIdentifier.${parammap.binding} IS NULL "},
                                            formatvalue : {value -> value }],
                                isnotnull:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.isnotnull",
                                            operator:"is not null",
                                            key:"isnotnull",
                                            dynamicQuery: {tableIdentifier, parammap-> " and $tableIdentifier.${parammap.binding} IS NOT NULL "},
                                            formatvalue : {value -> value }],
                                soundslike:[label:"net.hedtech.banner.ui.zk.search.advancedSearch.operator.soundslike",
                                            operator:"sounds like",
                                            key:"soundslike",
                                            dynamicQuery: {tableIdentifier, parammap-> " and ((soundex($tableIdentifier.${parammap.binding}) = soundex(:${parammap.key})) or :${parammap.key} is null)"},
                                            formatvalue : {value -> value }]
                              ]

        static final operatorGroups = [alphanumeric:[
                                            [operator:operators.contains, default:"true"],
                                            [operator:operators.startswith],
                                            [operator:operators.endswith],
                                            [operator:operators.equalsignorecase],
                                            [operator:operators.notequalsignorecase],
                                            [operator:operators.notequalsorisnull],
                                            [operator:operators.isnull],
                                            [operator:operators.isnotnull]
                                        ],
                                        numeric:[
                                            [operator:operators.equals, default:"true" ],
                                            [operator:operators.notequals],
                                            [operator:operators.notequalsorisnull],
                                            [operator:operators.numericbetween],
                                            [operator:operators.greaterthan],
                                            [operator:operators.greaterthanequals],
                                            [operator:operators.lessthan],
                                            [operator:operators.lessthanorisnull],
                                            [operator:operators.lessthanequals],
                                            [operator:operators.lessthanequalsorisnull],
                                            [operator:operators.isnull],
                                            [operator:operators.isnotnull]
                                        ],
                                        date:[
                                            [operator:operators.equals, default:"true" ],
                                            [operator:operators.between],
                                            [operator:operators.greaterthan],
                                            [operator:operators.greaterthanequals],
                                            [operator:operators.lessthan],
                                            [operator:operators.lessthanorisnull],
                                            [operator:operators.lessthanequals],
                                            [operator:operators.lessthanequalsorisnull],
                                            [operator:operators.isnull],
                                            [operator:operators.isnotnull]
                                        ],
                                        boolean:[
                                            [operator:operators.equals, default:"true"]
                                        ],
                                        checkbox:[
                                            [operator:operators.equalsorisnull, default:"true"]
                                        ],
                                        radio:[
                                            [operator:operators.equalsorisnull, default:"true"]
                                        ]

        ]
}
